name: Deploy to EKS

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - dev 
            - 'feature/*'

jobs:
    unit-tests:
        name: Unit Testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest

            - name: Run unit tests
              run: |
                pytest  
    
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        needs: unit-tests
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest pytest-cov

            - name: Run tests with coverage
              run: |
                pytest --cov=. --cov-report=xml

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                file: ./coverage.xml
                token: ${{ secrets.CODECOV_TOKEN }}

    docker-deploy:
        runs-on: ubuntu-latest
        needs: [unit-tests, code-coverage] 
        env:
            ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}  
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
            IMAGE_TAG: ${{ github.sha }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build Docker image
              run: |
                 docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

            - name: Push Docker image to ECR
              run: |
                docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG